package detect

var gazetteerNames = []string{
	"Kushal Subbayya Hegde",
	"Pushpa Kushal Hegde",
	"Rajesh Kushal Hegde",
	"Rohit Kushal Hegde",
	"Rakhi Girija Shetty",
	"Dinesh Hirachand Munot",
	"Ajay Shriram Patil",
	"Ram Kumar Tiwari",
	"Indu Jacob",
	"Sandesh Bhagwat",
	"Amod Joshi",
	"Sarthak Malvadkar",
	"Ganesh Prasad",
	"Lokesh Shah",
	"Soumavo Sarkar",
	"Kishan Rastogi",
	"Abhijit Diwan",
	"Shanti Gopalkrishnan",
	"Parag Pansare",
	"Pushpa Hegde",
}

var gazetteerCompanies = []string{
	"KSH International Limited",
	"KSH International Private Limited",
	"Bhandary Metal Extrusion Private Limited",
	"Waterloo Industrial Park VI Private Limited",
	"Waterloo Industrial Park I Private Limited",
	"Waterloo Industrial Park II Private Limited",
	"Waterloo Industrial Park III Private Limited",
	"Waterloo Industrial Park IV Private Limited",
	"Waterloo Industrial Park V Private Limited",
	"Waterloo Industrial Park VIII Private Limited",
	"Waterloo Industrial Park IX Private Limited",
	"Waterloo Industrial Park IX A Private Limited",
	"Waterloo Industrial Park IX B Private Limited",
	"Waterloo Motors Private Limited",
	"KSH Project Management Services Private Limited",
	"KSH Infra Park 5 Private Limited",
	"KSH Infra Park VI Private Limited",
	"KSH Infra Park IV Private Limited",
	"KSH Distriparks Private Limited",
	"KSH Integrated Logistics Private Limited",
	"Kushal Motors and Electricals Private Limited",
	"Kushal Electricals",
	"Waterloo Motors",
	"Parijat Foundation",
	"Dhaulagiri Family Trust",
	"Everest Family Trust",
	"Makalu Family Trust",
	"Broad Family Trust",
	"Annapurna Family Trust",
	"Kanchenjunga Family Trust",
	"Nuvama Wealth Management Limited",
	"ICICI Securities Limited",
	"ICICI Bank Limited",
	"HDFC Bank Limited",
	"MUFG Intime India Private Limited",
	"Link Intime India Private Limited",
	"Kirtane & Pandit LLP",
	"Kirtane & Pandit",
	"CARE Analytics and Advisory Private Limited",
	"CareEdge Research",
	"Trilegal",
	"Registrar of Companies, Maharashtra at Pune",
}

func NewGazetteerDetectors() []Detector {
	return []Detector{
		NewNameGazetteer(gazetteerNames),
		NewCompanyGazetteer(gazetteerCompanies),
	}
}